Controllers/AuthController.cs
using BarberShop.Application.BarberShop.Domain.Interfaces;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using BarberShop.Application.Models;
using BarberShop.Application.BarberShop.Domain.Helpers;
using BarberShop.Application.BarberShop.Domain.Entities;

namespace BarberShop.Application.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult NewLogin()
        {
            var newLogin = new NewLoginViewModel();

            return View(newLogin);
        }

        [HttpPost]
        public async Task<IActionResult> NewLogin(NewLoginViewModel newLogin)
        {
            if (ModelState.IsValid)
            {
                User userDB = _userService.GetByEmailOrPhone(Util.GetOnlyNumbers(newLogin.Celular));

                if (userDB == null)
                {
                    userDB = new User();
                    userDB.Name = newLogin.Nome;
                    userDB.Phone = Util.GetOnlyNumbers(newLogin.Celular);
                    userDB.YearOfBirth = newLogin.AnoNascimento;
                    userDB.Password = newLogin.AnoNascimento.EncodePasswordToBase64();

                    _userService.Add(userDB);
                }
                else
                {
                    ModelState.AddModelError("Celular", "Celular em uso por outro cadastro.");
                    return View(newLogin);
                }

                //Defina pelo menos um conjunto de claims...
                var claims = new List<Claim>
                {
                    //Atributos do usuário ...
                    new Claim(ClaimTypes.Name, userDB.Name),
                    new Claim(ClaimTypes.Role, "Comum"),
                    new Claim(ClaimTypes.MobilePhone, userDB.Phone),
                    new Claim(ClaimTypes.Hash, userDB.Code)
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    //IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };

                //Loga de fato
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                return RedirectToAction("Index", "Home");
            }

            return View(newLogin);
        }

        public IActionResult Login(string ReturnUrl)
        {
            var login = new LoginViewModel { ReturnURL = ReturnUrl };

            return View(login);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            var userDB = _userService.GetByEmailOrPhone(Util.GetOnlyNumbers(login.Celular));

            if (userDB == null)
                ModelState.AddModelError("Celular", "Celular não encontrado.");
            else
            {
                if (userDB.Password.DecodeFrom64() != login.Senha)
                    ModelState.AddModelError("Senha", "Senha incorreta.");
            }

            //Autenticar
            if (userDB != null && ModelState.IsValid)
            {
                //Defina pelo menos um conjunto de claims...
                var claims = new List<Claim>
                {
                    //Atributos do usuário ...
                    new Claim(ClaimTypes.Name, userDB.Name),
                    new Claim(ClaimTypes.Role, userDB.Administrator ? "Admin" : "Comum"),
                    new Claim(ClaimTypes.Hash, userDB.Code)
                };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    //IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };

                //Loga de fato
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                // Segura url vazia e url imbutida (somente redireciona para urls do sistema)
                if (!string.IsNullOrEmpty(login.ReturnURL) && Url.IsLocalUrl(login.ReturnURL))
                {
                    return Redirect(login.ReturnURL);
                }

                return RedirectToAction("Index", "Home");
            }

            return View(login);
        }

        public async Task<IActionResult> Logout()
        {
            // Clear the existing external cookie
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }

    }
}

Controllers/ManagementController.cs
using BarberShop.Application.BarberShop.Domain.Entities;
using BarberShop.Application.BarberShop.Domain.Helpers;
using BarberShop.Application.BarberShop.Domain.Interfaces;
using BarberShop.Application.BarberShop.Domain.Services;
using BarberShop.Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace BarberShop.Application.Controllers
{
    [Authorize]
    public class ManagementController : Controller
    {
        private readonly IUserService _userService;
        private readonly ISettingsService _settingsService;
        private readonly IPackageService _packageService;

        public ManagementController(IUserService userService, ISettingsService settingsService, IPackageService packageService)
        {
            _userService = userService;
            _settingsService = settingsService;
            _packageService = packageService;
        }
        public IActionResult Home()
        {

            var users = _userService.Get().Select(i => new UserViewModel(i)).ToList();

            return View(users);
        }

        [HttpGet]
        [Route("/Management/Details/{code}")]
        public IActionResult Details(string code)
        {
            var userDB = _userService.Get(code);

            return View(new UserViewModel(userDB));
        }

        [HttpPost]
        public IActionResult Details(UserViewModel user)
        {
            if (user != null && ModelState.IsValid)
            {
                var userDB = _userService.Get(user.Code);

                userDB.Name = user.Name;
                userDB.Phone = Util.GetOnlyNumbers(userDB.Phone);
                userDB.Email = user.Email;
                userDB.YearOfBirth = user.YearOfBirth;

                if (!String.IsNullOrEmpty(user.Password))
                {
                    userDB.Password = user.Password.EncodePasswordToBase64();
                }

                _userService.Edit(userDB);

                ViewBag.message = "Success";
            }

            return View(user);
        }

        public IActionResult CreateUser()
        {
            return View(new UserViewModel() { Code = "NeWCoDe" });
        }

        [HttpPost]
        public IActionResult CreateUser(UserViewModel user)
        {
            if (user != null && ModelState.IsValid)
            {
                User userDB = _userService.GetByEmailOrPhone(Util.GetOnlyNumbers(user.Phone));

                if (userDB != null)
                {
                    ModelState.AddModelError("Phone", "Celular em uso por outro cadastro.");
                    return View(user);
                }

                userDB = new User();
                userDB.Name = user.Name;
                userDB.Phone = Util.GetOnlyNumbers(user.Phone);
                userDB.Email = user.Email;
                userDB.YearOfBirth = user.YearOfBirth;

                if (!String.IsNullOrEmpty(user.Password))
                {
                    userDB.Password = user.Password.EncodePasswordToBase64();
                }
                _userService.Add(userDB);

                ViewBag.message = "Success";
            }

            return View(user);
        }

        public IActionResult Packages()
        {
            var packages = _packageService.Get();
            var packagesVW = packages.Select(e => new PackageViewModel(e)).ToList();

            return View(packagesVW);
        }

        [Route("/Management/DetailsPackage/{code}")]
        public IActionResult DetailsPackage(string code)
        {
            var package = _packageService.Get(code);

            return View(new PackageViewModel(package));
        }
        
        public IActionResult CreatePackage()
        {
            return View();
        }

        public IActionResult DayWork()
        {
            var settingsDays = _settingsService.GetByType(TypeSettings.DayWork);

            // Creating a custom list of weekdays in the desired order
            List<string> weekdaysOrder = new List<string>
            {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            };

            // Sorting the list of objects based on the custom order of weekdays
            var sortedList = settingsDays.OrderBy(e => weekdaysOrder.IndexOf(e.Identifier)).ToList();

            return View(sortedList.Select(i => new SettingsDayWorkViewModel(i)).ToList());
        }

        [HttpPost]
        [Route("/api/management/setdaywork")]
        public IActionResult SetDayWork([FromBody] SettingsDayWorkViewModel settingsDay)
        {
            var dayDB = _settingsService.Get(settingsDay.Code);

            if (dayDB != null)
            {
                dayDB.Start = settingsDay.Start;
                dayDB.End = settingsDay.End;
                dayDB.Value = settingsDay.Open.ToString();

                _settingsService.Edit(dayDB);
            }

            return Ok("Sucesso");
        }
        
        public IActionResult ReservedTimes()
        {
            return View();
        }

        [HttpGet]
        [Route("/api/management/getreservedtimes")]
        public IActionResult GetReservedTimes()
        {
            var reservedtimes = _settingsService.GetByType(TypeSettings.ReservedTimes);

            var reservedtimesVM = reservedtimes.Select(i => new ReservedTimeViewModel(i)).ToList();

            return Ok(reservedtimesVM);
        }

        [HttpPost]
        [Route("/api/management/createreservedtime")]
        public IActionResult CreateReservedTime([FromBody] ReservedTimeViewModel reservedTime)
        {

            var reservedTimeDB = new Settings()
            {
                Code = Guid.NewGuid().ToString(),
                Description = reservedTime.Description,
                Start = reservedTime.Hour,
                Identifier = Util.ConvertDayOfWeekPortugueseToEnglish(reservedTime.Day),
                TypeSettings = TypeSettings.ReservedTimes,
            };

            _settingsService.Add(reservedTimeDB);

            return Ok(reservedTimeDB.Code);
        }

        [HttpPost]
        [Route("/api/management/deletereservedtime")]
        public IActionResult DeleteReservedTime([FromBody] string code)
        {
            var reservedTimeDB = _settingsService.Get(code);
            _settingsService.Delete(reservedTimeDB);

            return Ok("Sucesso");
        }

    }
}

Controllers/ProfileController.cs
using BarberShop.Application.BarberShop.Domain.Helpers;
using BarberShop.Application.BarberShop.Domain.Interfaces;
using BarberShop.Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BarberShop.Application.Controllers
{
    // [Authorize(Policy = "Admin")]
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IUserService _userService;
        private readonly IAppointmentService _appointmentService;

        public ProfileController(IUserService userService, IAppointmentService appointmentService)
        {
            _userService = userService;
            _appointmentService = appointmentService;
        }

        public IActionResult Profile()
        {
            var claims = HttpContext.User.Claims;
            string code = HttpContext.User.Claims.First(c => c.Type == ClaimTypes.Hash).Value;
            var userDB = _userService.Get(code);

            var userVM = new UserViewModel(userDB);

            return View(userVM);
        }

        [HttpPost]
        public IActionResult Profile(UserViewModel user)
        {


            if (user != null && ModelState.IsValid)
            {
                var userDB = _userService.Get(user.Code);

                userDB.Name = user.Name;
                // userDB.Phone = Util.GetOnlyNumbers(user.Phone);
                userDB.Email = user.Email;

                _userService.Edit(userDB);

                ViewBag.message = "Success";
            }
            else
            {
                ModelState.AddModelError("Phone", "Celular preenchido incorretamente.");
            }

            return View(user);
        }

        public IActionResult MyAppointments()
        {
            var claims = HttpContext.User.Claims;
            string code = HttpContext.User.Claims.First(c => c.Type == ClaimTypes.Hash).Value;

            // TODO: Uma busca que retorna somente itens da pessoa logada
            var allAppointments = _appointmentService.Get().Where(a => a.ClientCode == code).ToList();

            var appointments = allAppointments.Select(i => new AppointmentViewModel(i)).ToList();

            return View(appointments);
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor
@{
    string nameUser = string.Empty;
    string role = string.Empty;

    if (httpContextAccessor.HttpContext != null &&
        httpContextAccessor.HttpContext.User != null &&
        httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name) != null)
    {
        nameUser = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Name).Value;
        role = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Role).Value;
    }
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BarberShop.Application.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarberShop.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Outro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="MyAppointments">Meus Agendamentos</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gerenciamento
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Management" asp-action="Home">Clientes</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Management" asp-action="Packages">Pacotes</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Management" asp-action="DayWork">Horários Funcionemento</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item text-dark" asp-area="" asp-controller="Management" asp-action="ReservedTimes">Horários Reservados</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <div class="d-flex" role="search">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Profile">@nameUser</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Sair</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BarberShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <input type="hidden" id="inputHiddenRole" name="inputHiddenRole" value="@role">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutClean.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarberShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BarberShop.Application.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>